OUTPUT_DIR = "results"
SUBDIRS = ["data", "graphs", "models", "spatial"]

FIGHT_TIMEOUT_S = 5.0
VOXEL_SIZE = 100
DEFAULT_HEALTH = 10.0
STAMPS_PER_SECOND = 40.0
CSV_SAMPLE_COUNT = 1
STAMPS_THRESHOLD = 30
HIGH_SPEED_THRESHOLD = 1000
MIN_NUM_EVENTS = 10
USE_SINGLE_CORE = False